# Generated by Django 5.0.4 on 2026-06-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famoso',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='famoso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='famosos/'),
        ),
    ]
