# Generated by Django 5.0.4 on 2026-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_remove_famoso_imagen_url_famoso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famoso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
