# Generated by Django 5.0.4 on 2026-08-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_alter_famoso_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='famoso',
            options={'permissions': [('puede_moderar', 'Puede acceder al panel de moderación y gestionar famosos')]},
        ),
    ]
